### ISSUE TITLE
Glitch (sprite priority issue?) in Kabuki Klash

### ISSUE THREAD

**Issue by mapfde** [MiSTer-devel/NeoGeo_MiSTer#141] opened 2021-09-19 14:03 UTC
The "versus" screens show a glitch: the screen shows the 2 character portraits and the "vs" text. The sprite of the portrait to the right is over the "vs" instead of under. 

The glitch shows up every time and can easily be reproduced.

**Comment by PepAlacant** [comment] 2021-10-31 11:15
It affects other games like Robo Army ( zooming letters at the intro ), Breakers Revenge ( VS portrait ), Legend of Success Joe ( winning scene at the stadium screen ), Kof 2003 ( intro )

**Comment by JackWitherell** [comment] 2022-04-02 08:10
I got some video of Legend of Success Joe as I noticed it in this game quite quickly.
Two examples
I'm not sure if this one is actually an example and would have to be verified against a real neo geo but the edges of the screen when you die in the ring looks suspect.

https://user-images.githubusercontent.com/4626546/161373499-ffc7cf5b-fcc1-468b-97b0-da67bb7fa53b.mp4

This however, is a true example and should very much be fixed/fixable/testable easily. When you complete a battle in the ring, (any battle, level 2 should do and is relatively easy to breeze through), the sprites that display inside of the box overflow into the region outside of the box to the right.

https://user-images.githubusercontent.com/4626546/161373504-5c4a6cad-9060-4fb0-8b36-1c32920cd91e.mp4

**Comment by PepAlacant** [comment] 2022-04-20 19:57
The edges of the ring are normal. That's the overscan and exists in the real hardware. The second video is the same issue with Kabuki, Robo Army, Breakers Revenge...

**Comment by paulb-nl** [comment] 2022-12-05 19:56
Try the build from here: 
https://github.com/MiSTer-devel/NeoGeo_MiSTer/issues/26#issuecomment-1338082616

**Comment by Toryalai1** [comment] 2022-12-08 21:25
The edges on Legend of success joe is not a bug, its part of the overscan. It's because you've set Width to 320px (AES). The game was only released for MVS which is 304px.

Other than that, all of the mentioned bugs in this ticket are solved now thanks to paulb-nl

**Comment by paulb-nl** [comment] 2022-12-24 16:51
Fixed in release 20221224

**Closed** 2022-12-25 22:14 UTC
