### ISSUE TITLE
Neo Geo core pitch sound issues, as well as sound speed.  

### ISSUE THREAD

**Issue by Bocop** [MiSTer-devel/NeoGeo_MiSTer#111] opened 2020-10-14 13:38 UTC
Sound in many games has wrong pitch and even shifting pitch in Blazing Star music. It is definitely there and noticable. It sounds like the music slows down and speeds up changing pitch ever so slightly.

**Comment by rsn8887** [comment] 2020-10-14 18:41
I also hear this in Blazing Star.

**Comment by rsn8887** [comment] 2020-10-14 18:43
I think this might be a duplicate issue, see here https://github.com/MiSTer-devel/NeoGeo_MiSTer/issues/60

**Comment by Bocop** [comment] 2020-10-14 18:48
> I think this might be a duplicate issue, see here #60

Yeh this seems to be ongoing because people can still hear it in Blazing Star and a few other games.  I just read through that whole thread and it is awesome that @jotego is working through it with people who can hear this.   The Neo Geo core is my favorite and I think it's amazing.

**Comment by MJY71** [comment] 2020-10-18 16:00
It's really noticeable during the title music for Pulstar as well, about 30 seconds in after loading the game once the gameplay demo starts and there is action on-screen (shots being fired, ships exploding, etc.). The music speed and pitch really starts dragging as though it's being played back on an analog reel-to-reel player with a dirty head.

It doesn't exhibit this behavior when played back in the game's Options screen in AES mode.

**Comment by MonokromFR** [comment] 2020-10-21 20:40
Hi all !
Can't compare as i never own Pulstar on real hardware but notice something "wrong" in Pulstar demo sound.
Issue seems to disappear when soundtrack are played (alone) on AES mode or in Unibios jukebox.

This is the same issue as https://github.com/MiSTer-devel/NeoGeo_MiSTer/issues/60
Pitch issue appears when SFX are played at the same time.

This was more noticable before Last Neogeo core update (2020-09-28)

**Comment by Bocop** [comment] 2020-10-22 15:46
Is it still a thing after the last update? did the last update help anything?   Is there an update that also has not been released yet?

**Comment by Bocop** [comment] 2020-12-07 20:10
@MJY71  That is too bad.  Ugh.

**Comment by pacoarcade** [comment] 2021-01-17 15:27
I also notice this, specially on seconds 15s, 19s, 25s and 27s of my audio capture:

[blazingstar.zip](https://github.com/MiSTer-devel/NeoGeo_MiSTer/files/5826313/blazingstar.zip)

**Comment by Bocop** [comment] 2021-01-20 14:49
> Hi, this is the author of JT12, which was forked on this repository to handle the sound. If you can produce VGM files of the relevant music tracks where the problem occurs I will check if the problem is in JT12. Thank you.

@jotego  @pacoarcade  Just put up a sound sample of the issue.   Any chance you could take a look at this? thank you so much!

**Comment by pacoarcade** [comment] 2021-01-20 14:59
@Bocop I already uploaded an audio capture via recorder. If needed I could look to make the recording via line in.

**Comment by Bocop** [comment] 2021-01-20 15:01
Oh, I was referencing the one you posted, thank you so much!!!

**Comment by okami2012** [comment] 2021-03-29 12:32
Excuse me ,I saw NEO GEO core sound is run a slower than video like The King of Fighter 98. In the Opening Video

**Comment by Bocop** [comment] 2021-03-29 12:41
Good to know!  I would love if this core got an update that ironed out any
of the remaining sound issues.

**Comment by stainmage** [comment] 2021-04-19 09:26
Hello, since this thread has an older duplicate, I post my comment there too 👍 

Same problem here but I noticed the pitch variation in every game I tested : Art of Fighting, Kof98, Snk vs Capcom...

Here is a comparison between the latest mister core 128mb, and a real neo geo with Darksoft cartridge, it's the same romset :

https://drive.google.com/file/d/1szaYSXKVfdZ9bnq_-mSRIFflALAyzSgA/view?usp=drivesdk

https://drive.google.com/file/d/1sqCVhe7P5jOVbZtC4V_RC36oJ95ZnUSW/view?usp=drivesdk

You can sense after pressing the start button how the second note drifts away in some kind of modulation while the computer shows the tutorial.

There are many parts of the game that has the same problem.

Hard to tell in the video but IRL it's easy to spot, sounds like a tape slow down

Cheers

**Comment by Matt-Retrogamer** [comment] 2021-06-17 09:50
Hi guys,

Any update of this topic ?
It was also reported by a couple of users on our Discord channel.

thx!

**Comment by Bocop** [comment] 2021-06-17 15:09
I have seen nothing in a really long time.  Was hoping it would be taken
care of.  :-(

**Comment by mirkorean** [comment] 2021-08-11 20:48
There was a fix merged for this. Maybe you guys can try the build from here: https://github.com/MiSTer-unstable-nightlies/NeoGeo_MiSTer/releases/download/unstable-builds/NeoGeo_unstable_20210811_ba00.rbf and report back?

**Comment by MonokromFR** [comment] 2021-08-11 21:47
> There was a fix merged for this. Maybe you guys can try the build from here: https://github.com/MiSTer-unstable-nightlies/NeoGeo_MiSTer/releases/download/unstable-builds/NeoGeo_unstable_20210811_ba00.rbf and report back?

THAT
IS
A
GREAT
NEW !!!

Works like a charme !
I don't hear any f***ng warble sound anymore.

**Comment by stainmage** [comment] 2021-08-13 07:18
Hi, thanks a lot for this fix, I can confirm I don't hear the problem anymore in Art of Fighting

**Comment by Bocop** [comment] 2021-08-13 15:24
I'm stuck at work at the moment, can anyone try Pulstar and Mark of Wolves?  I know they were 2 games with some funny pitch issues.

**Comment by darkphoenixfox** [comment] 2021-08-13 15:26
Pulstar sounds perfect now (and AOF3 too, which also had clear issues)

**Comment by Bocop** [comment] 2021-08-13 15:30
Awesome, thanks!   Wow, this release is going to be amazing.

**Comment by AtomicShroom** [comment] 2021-08-20 14:46
Yup, sounds great with the latest change!  Thank you so much! :D

**Comment by Dubon77** [comment] 2021-09-14 16:53
Please close this issue

**Closed** 2021-09-14 18:00 UTC
