### ISSUE TITLE
Zed Blade / Operation Ragnarok sound issue

### ISSUE THREAD

**Issue by Klatrymadon** [MiSTer-devel/NeoGeo_MiSTer#138] opened 2021-08-24 14:25 UTC
Hi,

In Zed Blade, it's possible for the title screen music to burst in at any moment during a stage, and play for the remainder of that level. I'm not sure what triggers it, so I can't reproduce it deliberately, but it can seemingly happen on any stage, and as early as the opening of stage 1. This is consistent across the main release of the core and the 'unstable' build which fixes a lot of the other sound issues (thanks so much for that - Zed Blade had lots of others!), though I'm tempted to say it's less frequent on the latter.

Thanks for reading, and please let me know if there's anything I can do to investigate further. :)

**Comment by paulb-nl** [comment] 2023-01-07 21:01
Are you sure this is not normal behavior for this game?

How often does this happen? If we can't reproduce this reliably then fixing this is extremely difficult.

I have been starting and resetting the game a number of times trying to make it happen in the opening of stage 1 but couldn't reproduce it.

**Comment by sorgelig** [comment] 2023-07-29 22:59
No reply from OP and no other ppl mentioned this issue.
Probably it was part of instability from async clocks.
Closing as unconfirmed.

**Closed by sorgelig** 2023-07-29 22:59 UTC
