### ISSUE TITLE
Graphical glitch in king of the monsters

### ISSUE THREAD

**Issue by acky6012** [MiSTer-devel/NeoGeo_MiSTer#97] opened 2020-07-23 23:52 UTC
Using gog rom, when in game, the scrolling on the left side of the screen is a bit odd. As screen scrolls, the left edge stays put for a second and then snaps left into place. A small section of the edge  about a third of the way down scrolls correctly while the rest is snapping.

I'm using hdmi on a samsimg syncmaster monitor/tv, just scan.

Mister settings are 1080p 60hz, low lag vsync adjust, vscale integer only.

Not sure what other info might be relevant, so just holler if you need any other details.

Many thanks!

**Comment by rhester72** [comment] 2020-09-29 18:50
This is how Neo Geo worked and the reason some emulators offer the ability to mask one or both sides of the screen.  It was often masked by screen edges (due to use of overscan) on original hardware.  It's not a bug.

**Comment by acky6012** [comment] 2020-09-30 06:22
Cool.
Thanks for replying!

**Comment by Dubon77** [comment] 2021-09-14 16:55
Please close this issue

**Closed** 2021-09-14 18:00 UTC
