### ISSUE TITLE
Last 27th unstable problems.

### ISSUE THREAD

**Issue by PepAlacant** [MiSTer-devel/NeoGeo_MiSTer#201] opened 2023-07-27 16:21 UTC
Zoomglitching seems to be fixed.
KOF 94 MVS/AES flickers so bad, CD version misteriously works perfect.
PAL MODE : The RASTER EFFECT is completely desynced. So sure that almost nobody plays in PAL, but it didn't happen in the 19th unstable.

Things like the staff roll in AOF 3 seems to be related to UNIBIOS and certain cheats enabled. It can be an UNIBIOS problem, and not the core. Needing confirmation from real hardware.

**Comment by sorgelig** [comment] 2023-07-28 00:50
> PAL MODE : The RASTER EFFECT is completely desynced. So sure that almost nobody plays in PAL, but it didn't happen in the 19th unstable.

please provide testing instructions

**Comment by sorgelig** [comment] 2023-07-28 01:46
I've tried KOF94 and didn't find abnormal flickering. Although i'm not familiar with this game. Where it flickers?

**Comment by wwark** [comment] 2023-07-28 05:19
The flickering is present at the end of each battle on the text. It flickers on the right part of the text.

**Comment by paulb-nl** [comment] 2023-07-28 05:48
Text flickering might be caused by Universe Bios. Try original bios.

**Comment by paulb-nl** [comment] 2023-07-28 06:02
The raster effect is broken on the first stage of World Heroes 2 Jet in pal mode. I'll check out the timer

**Comment by wwark** [comment] 2023-07-28 06:04
> Text flickering might be caused by Universe Bios. Try original bios.

I used only original bios. Cheking with the last commit https://github.com/MiSTer-devel/NeoGeo_MiSTer/commit/7ba6bce53481e3f1d43a210184282bf6a6bdeef4 build with autobuild it is still present with original bios.

**Comment by wwark** [comment] 2023-07-28 06:08
I link the previous issue related to KoF 94 maybe it could help to see at which commit it was previously fixed in the past
https://github.com/MiSTer-devel/NeoGeo_MiSTer/issues/73

**Comment by PepAlacant** [comment] 2023-07-28 06:59
Flickering in KOF 94 can be saw immediately in the HOW TO PLAY screen. Ryo Sakazaki sprite is not stable. From Right to left, pieces of sprites here and there.  The flickering of texts is a consequence of this too.

**Comment by paulb-nl** [comment] 2023-07-28 10:03
If it also happens with bootleg carts then it points to rom speed issue. 

Try adding `rom_wait="1"` to kof94 in romsets.xml same as with ninja commando here:
https://github.com/MiSTer-devel/NeoGeo_MiSTer/blob/7ba6bce53481e3f1d43a210184282bf6a6bdeef4/releases/romsets.xml#L115

It fixed the glitches for me.

**Comment by wwark** [comment] 2023-07-28 14:54
testing KOF94 with the new romset.xml it is working great with darksoft rom thank you :)

**Comment by PepAlacant** [comment] 2023-07-28 18:24
Rasters and KOF 94 Fixed !

**Comment by sorgelig** [comment] 2023-07-28 19:01
If everything from OP is fixed then please close the issue.

**Closed** 2023-07-28 19:14 UTC
