### ISSUE TITLE
The Super Spy Audio Bug

### ISSUE THREAD

**Issue by fignutz** [MiSTer-devel/NeoGeo_MiSTer#164] opened 2022-05-20 01:59 UTC
As of the 20220403 release, "The Super Spy" has a bug where certain portions of the audio's music has extremely high-pitched tones play intermittently during both gameplay and attract sequences. This phenomenon only happens during the main execution of the game logic and not boilerplate logic such as the Neo Geo attract logo music.

**To Recreate:**
1. Use/load "DarkSoft Roll-Up Pack" version of The Super Spy
2.  Set Uni-Bios 4 to U.S.A./ARCADE
3. Let game play in attract mode and listen.

**Comment by PepAlacant** [comment] 2022-05-24 20:23
I cannot get the error. What it's exactly. Which instrument ? I'll compare with real hardware.

**Comment by fignutz** [comment] 2022-05-24 22:19
I'm not sure which instrument is playing wrong by name. If I had to guess, its what ever instrument that plays the main theme lead in music in the high-pitched areas right before the announcer exlcaims "The Super Spy". I own the MVS cart myself, and I can confirm this high-pitched squeal does not exist on my MVS playthroughs. 

That said, I use the  commercial (non-free) older 3.x UNIBIOS on my 4 Slot cabinet, and have not upgraded to UNIBIOS 4.0 that is pulled into the MiSTer via the 'update_all.sh" script. I point this out because, until a certain update occurred with the UniBIOS v3 (I think 3.1 to 3.5?), the "hands/fists" or the "Main title logo" of "The Super Spy" would not show up.

**Comment by PepAlacant** [comment] 2022-05-25 07:06
I cannot reproduce these pitches in my MiSTer.

**Comment by fignutz** [comment] 2022-05-25 09:35
That's fine, but I'd like to see if @sorgelig or @jotego can replicate this issue, as I am still seeing this phenemenon. This is the only NeoGeo game this happens with, as all of the other ones test fine.

**Comment by sorgelig** [comment] 2022-05-25 10:45
This core has some design flaw using async clocks which may introduce issues for some (not all) users. It cannot be simply fixed. Core needs some re-writing. @furrtek has plans to do it, so let's wait for it.

**Comment by fignutz** [comment] 2022-05-25 15:09
Thanks for that insight @sorgelig; much appreciated. FWIW, I am still going to try downgrading my BIOS to the version I use with my real MVS just to see if the issue persists. Again, this may be moot given your note on async clocks, but I'd like to rule it out all the same.

**Comment by Dubon77** [comment] 2022-08-22 06:17
@sorgelig @furrtek fwiw, the developer who ported this core to analogue pocket claims to have fixed this design flaw, however he doesnt have a mister and so will not backport these changes himself. The repo is at https://github.com/Mazamars312/Analogue_Pocket_Neogeo

**Comment by sorgelig** [comment] 2022-08-22 14:18
Mazamars312 is furrtek? I don't think so. Also furrtek has MiSTer.
If we talk about design flaw which means async clocks, then it's not fixed. All async clocks are there. 
As for specific issue - need further checking. I don't have Analogue Pocket to verify it. Since async clocks give many race conditions in core, it can be "fixed" for some users but not for everyone.

**Comment by kold669** [comment] 2022-11-26 14:08
It happens also on Ghost Pilot, same high pitched notes as Super spy

**Comment by kold669** [comment] 2023-01-27 19:30
Great! changing vromb_offset to 0x200000 for both games in romset.xml did the trick!

**Comment by Toryalai1** [comment] 2023-07-28 08:59
@kold669 Since it fixed the problem, you can close this issue

**Closed** 2023-07-28 09:20 UTC
