### ISSUE TITLE
Breaker's Revenge - Graphical issue with "VS"

### ISSUE THREAD

**Issue by cacophony1** [MiSTer-devel/NeoGeo_MiSTer#26] opened 2019-09-08 17:40 UTC
I originally saw this in a MiSTer stream yesterday, but just reproduced with the latest software (rbf, main, menu, xml). The "VS" gets cut off in the intro to any match in Breaker's Revenge.

See the screenshot here:
![breakers_revenge](https://user-images.githubusercontent.com/6505207/64492088-de323a00-d224-11e9-9eb5-ddb05fa46cbb.png)

**Comment by sorgelig** [comment] 2019-09-08 19:11
weird issue since original Breakers game has no such issue.. 
May be bad dump?

**Comment by cacophony1** [comment] 2019-09-09 02:32
Here's an image from a MVS-1C + Darksoft multicart, using what I assume is the same rom (this came from @loloC2C )

![IMG_1347](https://user-images.githubusercontent.com/6505207/64499794-5d4c6000-d26f-11e9-93a5-c175ce53b111.jpg)

**Comment by M-Walrus** [comment] 2019-09-09 04:52
The original Breakers is very similar to Breakers Revenge, so I checked in original Breakers for this same behavior. It does seem to have the same VS logo, but is completely visible there, no glitch like this in original Breakers. 
Usually wouldn't compare two different games like this, but because they are so similar I thought it might help.

**Comment by loloC2C** [comment] 2019-09-09 21:57
I double-checked by copying the rom from the SD card I use on the Darksoft MVS multi to the one I use for the MiSTer and confirm that using the exact same rom the bug only occur with the MiSTer core.

**Comment by asturur** [comment] 2021-09-12 13:57
a very similar error happen  on fast est of eden. i took a screenshot with the phone i ll post it

**Comment by Tuxosaurus** [comment] 2022-07-04 19:39
I saw this bug today - I had played the game on MiSTer before but I imagine I was mashing through this screen.
Nothing new to report, also using the Darksoft set.

**Comment by paulb-nl** [comment] 2022-12-05 19:54
I have found the cause of this issue.  Here is a build with the fix. Please test this build to make sure it does not cause issues with other games.

[NeoGeo_20221205.rbf.zip](https://github.com/MiSTer-devel/NeoGeo_MiSTer/files/10157430/NeoGeo_20221205.rbf.zip)

**Comment by Toryalai1** [comment] 2022-12-08 21:33
This is solved with the latest fix by paulb-nl

**Comment by paulb-nl** [comment] 2022-12-24 16:55
Fixed in release 20221224

**Closed** 2022-12-25 22:13 UTC
