### ISSUE TITLE
Extended sustain (Sound) on Money Idol Exchanger samples.

### ISSUE THREAD

**Issue by pepinw** [MiSTer-devel/NeoGeo_MiSTer#67] opened 2020-01-08 22:36 UTC
I'll admit there have been many improvements in the NeoGeo cores, but this one seems more like a regression.

Core version: 19.12.05

Play any mode of the game, or watch the attract loop.

You'll here when the coins connect in the field, there's a ... WAY longer sustain on the coin connect sound, which takes it from a short "clink" to a long "beeeeeeeeeeeeeeeeeeeeeeeep" --

In the previous version of the core (or jt's sound core) this did not happen.

**Comment by pepinw** [comment] 2020-01-25 16:46
I decided to try older cores to figure out when the error happed in the build tree.

19.09.11 had the bug, the previous revision
19.09.07 does not have the bug.. so, it was introduced after that checkpoint.

**Comment by raygan** [comment] 2020-01-31 14:34
This is probably the same as the issue I submitted:
https://github.com/MiSTer-devel/NeoGeo_MiSTer/issues/56
I first tried the core around November, so I didn't realize it was a regression.

**Comment by KKnot007** [comment] 2020-02-03 23:19
Same here...coin sounds are creepy in the last core version

**Comment by sorgelig** [comment] 2020-02-12 21:28
added the commit fixing this issue

**Comment by M-Walrus** [comment] 2020-09-29 11:06
This issue was fixed and should be closed. 

As noted above, this is a duplicate of issue #56 , which was already closed out.

**Closed** 2020-09-29 17:41 UTC
